[package]
name = "pros"
version = "0.1.0"
authors = ["serxka <serxka@protonmail.com>"]
edition = "2021"

[lib]
name = "pros"
path = "src/lib.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
libc-print = "0.1"
bitflags = "1"
num-traits = { version = "0.2", default-features = false }
num-derive = { version = "0.3", default-features = false }
smallvec = "1.7"

[build-dependencies]
zip = { version = "0.5", default-features = false, features = ["deflate"] }
bindgen = "0.58"
