[package]
name = "pros"
version = "0.1.0"
authors = ["serxka <serxka@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
name = "pros"
path = "src/lib.rs"

[dependencies]
libc = { version = "0.2", default-features = false }
libc-print = "0.1"

[build-dependencies]
zip = { version = "0.5", default-features = false, features = ["deflate"] }
bindgen = "0.58"
